/**
 * ECF 4.01 Representative XML Generator
 *
 * Transforms the internal FilingPacket into a representative ECF 4.01-style XML payload.
 * This is NOT Florida-certified XML — it is a structurally accurate representation
 * to demonstrate architectural readiness for real Florida XSD compliance.
 *
 * When Florida XSDs are obtained, ONLY this file needs to change.
 * All business logic remains intact.
 */

import type { FilingPacket } from './courtFilingProvider';

function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

export function generateECFXml(packet: FilingPacket, submissionId: string): string {
  const ts = new Date().toISOString();

  const partiesXml = packet.parties.map((p, i) => `
    <ecf:CaseParticipant>
      <nc:EntityPerson s:id="party${i + 1}">
        <nc:PersonName>
          <nc:PersonFullName>${escapeXml(p.name)}</nc:PersonFullName>
        </nc:PersonName>
      </nc:EntityPerson>
      <ecf:CaseParticipantRoleCode>${escapeXml(p.role.toUpperCase())}</ecf:CaseParticipantRoleCode>
    </ecf:CaseParticipant>`).join('');

  const documentsXml = packet.documents.map((d, i) => `
    <ecf:Document s:id="doc${i + 1}">
      <nc:DocumentIdentification>
        <nc:IdentificationID>${escapeXml(d.documentId)}</nc:IdentificationID>
      </nc:DocumentIdentification>
      <nc:DocumentCategoryCode>${escapeXml(d.type.toUpperCase())}</nc:DocumentCategoryCode>
      <nc:DocumentFileName>${escapeXml(d.fileName)}</nc:DocumentFileName>
      <ecf:DocumentIsLeadDocumentIndicator>${d.isLead ? 'true' : (i === 0 ? 'true' : 'false')}</ecf:DocumentIsLeadDocumentIndicator>
      <ecf:DocumentRendition>
        <ecf:DocumentRenditionMetadata>
          <ecf:DocumentSignature>
            <ds:Reference URI="#doc${i + 1}">
              <ds:DigestValue>${escapeXml(d.sha256)}</ds:DigestValue>
            </ds:Reference>
          </ecf:DocumentSignature>
        </ecf:DocumentRenditionMetadata>
        <!-- PDF content transmitted as base64 attachment in production -->
      </ecf:DocumentRendition>
    </ecf:Document>`).join('');

  return `<?xml version="1.0" encoding="UTF-8"?>
<!--
  REPRESENTATIVE ECF 4.01-STYLE XML
  Generated by: Yaffa Law AI Filing System
  Note: This XML is structurally representative of ECF 4.01 (OASIS).
        It is NOT Florida-certified XSD-compliant XML.
        Florida-specific XSD compliance will be implemented post-TPV certification.
  Generated: ${ts}
  Submission ID: ${submissionId}
-->
<ecf:RecordDocketingMessage
  xmlns:ecf="urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:CommonTypes-4.01"
  xmlns:nc="urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:NIEM-Core-4.01"
  xmlns:j="urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:CriminalCase-4.01"
  xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
  xmlns:s="http://niem.gov/niem/structures/2.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <ecf:SendingMDELocationID>
    <nc:IdentificationID>YAFFA-LAW-OS-V1</nc:IdentificationID>
  </ecf:SendingMDELocationID>

  <ecf:SendingMDEProfileCode>urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:FilingListMessage-4.01</ecf:SendingMDEProfileCode>

  <ecf:MessageContentsFiling>
    <ecf:FilingCaseInformation>
      <nc:CaseCategoryCode>${escapeXml(packet.caseType)}</nc:CaseCategoryCode>
      <nc:CaseTrackingID>${escapeXml(packet.caseId)}</nc:CaseTrackingID>
      <ecf:FilingTypeCode>${escapeXml(packet.filingType.toUpperCase())}</ecf:FilingTypeCode>
      <ecf:CourtCode>${escapeXml(packet.courtCode)}</ecf:CourtCode>
      <ecf:FilingDate>${ts}</ecf:FilingDate>
      ${partiesXml}
    </ecf:FilingCaseInformation>

    <ecf:FilingDocuments>
      ${documentsXml}
    </ecf:FilingDocuments>

    <ecf:FilingAttorney>
      <nc:PersonName>
        <nc:PersonFullName>${escapeXml(packet.submittedBy.name)}</nc:PersonFullName>
      </nc:PersonName>
      <ecf:AttorneyBarMembership>
        <ecf:BarMembershipID>${escapeXml(packet.submittedBy.barNumber)}</ecf:BarMembershipID>
        <ecf:BarMembershipJurisdiction>Florida</ecf:BarMembershipJurisdiction>
      </ecf:AttorneyBarMembership>
    </ecf:FilingAttorney>

    <ecf:FilingFeeInformation>
      <!-- Fee calculation performed by court — see /sim/fees/calculate -->
    </ecf:FilingFeeInformation>
  </ecf:MessageContentsFiling>

</ecf:RecordDocketingMessage>`;
}
